[package]
name = "cudaalights-rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
byondapi = "0.1.0"
byondapi-sys = "0.8.0"
num-traits = "0.2"
rayon = "1.7.0"
rayon-hash = "0.5.0"